---
abstract: 'OATH One Time Passwords'
author:
  - 'Kurt Kincaid <kurt.kincaid@gmail.com>'
build_requires:
  Digest::HMAC: 0
  Digest::SHA1: 0
  Math::BigInt: 0
  Moose: 0
  Test::More: 0
  Test::Simple: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Authen-OATH
provides:
  Authen::OATH:
    file: lib/Authen/OATH.pm
    version: v1.0.0
resources:
  license: http://dev.perl.org/licenses/
version: v1.0.0
